server:
   port: 28080
   
spring:
   datasource.url: jdbc:mysql://localhost/issuetracker
   datasource.username: root
   datasource.password: password
   datasource.driverClassName: com.mysql.jdbc.Driver

   jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
   jpa.show-sql: true
   jpa.hibernate.ddl-auto: update
