server:
   port: 28080
   
spring:
   datasource.url: jdbc:mysql://172.17.0.2/nearshore
   datasource.username: root
   datasource.password: supersecret
   datasource.driverClassName: com.mysql.jdbc.Driver

   #jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
   jpa.show-sql: true
   #jpa.hibernate.ddl-auto: update
