server:
  port: 0
spring:
  application:
    name: nearshore-data-service
  
  datasource:
    url: jdbc:mysql://172.17.0.3/nearshore
    username: root
    password: supersecret
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate.ddl-auto: update
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
