spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
   
spring:
   datasource.url: jdbc:mysql://172.17.0.2/nearshore
   datasource.username: root
   datasource.password: supersecret
   datasource.driverClassName: com.mysql.jdbc.Driver

   jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
   jpa.show-sql: true
   jpa.hibernate.ddl-auto: update
   
   jackson:
    serialization:
      fail-on-empty-beans: false
