server:
  port: 0
spring:
  application:
    name: nearshore-login-service
  redis:
    host: 172.17.0.2
    port: 6379
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
