server:
   port: 8000

message: MENSAJE DESDE MEETUP LIVE CODING SESION

eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
   instance:
      preferIpAddress: true
spring:
   cloud:
      stream:
         bindings:
            input:
               destination: productos
               contentType: text/plain

